language: common-lisp
sudo: true

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t
  matrix:
    - LISP=sbcl-bin COVERALLS=true

install:
  - sudo apt-get install -y liblmdb0 liblmdb-dev
  # Roswell & coveralls
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls
  - git clone https://github.com/antimer/liblmdb ~/lisp/liblmdb

before_script:
  - ros --version
  - ros config

script:
  - ros -e '(ql:quickload (list :fiveam))'
        -e '(setf fiveam:*debug-on-error* t
                  fiveam:*debug-on-failure* t)'
        -e '(ql:quickload :lmdb-test)'
        -e '(lmdb-test:run-tests)'

notifications:
  email:
    - eudoxiahp@gmail.com
